# Generated by Django 5.0.6 on 2024-06-22 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrillingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'drilling_status',
            },
        ),
        migrations.CreateModel(
            name='TechStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tech_status',
            },
        ),
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('well_depth', models.IntegerField(help_text='Глубина скважины (сколько надо пробурить (в метрах))')),
                ('bottom_hole_drilling', models.IntegerField(help_text='Глубина бурения (сколько пробурили (в метрах))')),
                ('connection_speed', models.IntegerField(help_text='Скорость соединения (в Кб/с)')),
                ('tech_date', models.DateField()),
                ('drilling_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rig_status.drillingstatus')),
                ('tech_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rig_status.techstatus')),
            ],
            options={
                'db_table': 'rig',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
                ('rig_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rig_status.rig')),
            ],
            options={
                'db_table': 'sensor',
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rig_status.sensor')),
            ],
            options={
                'db_table': 'sensor_data',
            },
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['rig_id'], name='sensor_rig_id__ba5fee_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['sensor_id'], name='sensor_data_sensor__90dcbe_idx'),
        ),
        migrations.AddIndex(
            model_name='rig',
            index=models.Index(fields=['drilling_status_id'], name='rig_drillin_c49cee_idx'),
        ),
        migrations.AddIndex(
            model_name='rig',
            index=models.Index(fields=['tech_status_id'], name='rig_tech_st_81869d_idx'),
        ),
    ]
