# Generated by Django 5.0.6 on 2024-06-26 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rig_status', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='title',
            new_name='name',
        ),
    ]
