# Generated by Django 5.0.6 on 2024-06-26 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rig_status', '0002_rename_title_sensor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
